### ISSUE TITLE
メール配信のSendGridへの移行

### ISSUE THREAD

**Issue by mkizka** [mkizka/tsukuriga#115]
## 現状
ムームーメールを使っている。値段が倍になってたり送信履歴が見れなかったりで全体的にSendGridの方がよさそう

## やること
2021/03/14までにSendGridに移行する

**Comment by Hayakuchi0** [comment]
単に配信及び問い合わせ用のメールサーバーが欲しいだけでしたらpostfix+dovecotでいいような気がしますが、どうでしょう？
(暗号化されてないですが、私は以下の手順でSMTPサーバー立てて普段使いしてます)
https://centossrv.com/postfix.shtml

**Comment by mkizka** [comment]
メールサーバーは自分で管理すると闇らしいというのと、Sendgridの無料プランは12000通/月で今ツクリガの通知データが5000くらいしかなくこれで十分すぎるという判断です

**Comment by mkizka** [comment]
SendGridは審査があるらしいのでMailjetを試しに利用
