### ISSUE TITLE
フォロー機能の追加

### ISSUE THREAD

**Issue by Hayakuchi0** [mkizka/tsukuriga#117]
## 概要
そろそろ全作品新着順を消したい( #92 )ため、その準備としてお気に入り新着を復刻させる必要がある
お気に入り新着を復刻させるにはフォロー機能の搭載が必要になる

## やること
- [x] フォロー機能作成
- [x] お気に入り新着作成
- [x] フォロワー一覧ページ作成
- [x] フォロイー一覧作成

## 出来たらやる
* フォロー通知メールのテスト環境整備
  * mailcatcher
  * ↑が面倒そうなら`EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'`の設定

**Comment by mkizka** [comment]
issue立てありがとうございます。編集して整理しておきました
