### ISSUE TITLE
軽微なリファクタリング案まとめ

### ISSUE THREAD

**Issue by mkizka** [mkizka/tsukuriga#48]
### ~utils.jsのdoc関数を変更して適切な箇所を修正する~ 完了
* `doc` ... `document.querySelector`のエイリアス
* `docAll` ... `document.querySelectorAll`のエイリアス

`doc()[0]`とか`doc().forEach`みたいな記述を減らしたい

### ~Commentモデルの匿名対応用メソッドに`user_`のプレフィックスを付ける~ 完了
* `comment.user_username`
* notify.models.Notificationは`sender_`で対応済み

### ~Pointモデルの`username_display`と`json`メソッド修正~
* nameとusernameが逆になっている
* ほとんど未使用のメソッドなので急いで対応する必要はない

## ~browse.models内のfrom_datetime修正~ 完了
https://github.com/Compeito/tsukuriga/issues/48#issuecomment-489435652

**Comment by Hayakuchi0** [comment]
browse/models.pyのfrom_datetimeについて、self.day_countが0以下なら2019年4月1日(サービス開始時)からの経過時間を返す仕様に変更したいです
理由としては以下の2つです

* わざわざraiseしたりそれを回避する処理を入れると処理が増える、バグの原因も増える
*  Rankingオブジェクトが表している「無期限」の意味は「考えうる限り最も過去の時刻から現在が集計期間である」という意味であると解釈するのが自然だと思われる

**Comment by Compeito** [comment]
それ思いつかなかったです。是非お願いします

**Comment by Hayakuchi0** [comment]
了解です
人気順実装を終えたらリファクタのプルリクを送ります

**Comment by Hayakuchi0** [comment]
とりあえず明後日の23時までに送ります
変更は10行以内におさめます

**Comment by Compeito** [comment]
全て完了したのでクローズ

**Comment by Compeito** [comment]
**Commentモデルの匿名対応用メソッドにuser_のプレフィックスを付ける**のjs側の対応がまだだったので再オープン
よく見たらPointのjsonもおかしいので直す
