### ISSUE TITLE
Altwugアーカイブページの作成

### ISSUE THREAD

**Issue by mkizka** [mkizka/tsukuriga#91]
やること

- [x] Altwugの全動画をツクリガのストレージに移す
- [x] #75 の作成
- [x] コマ送りツールへの直リンク(/framebyframe?url=...)一覧を掲載したページの作成
- [x] 告知作成
- [x] Altwugアカウントによるログイン機能の削除
- [x] Altwug完全閉鎖

**Comment by Compeito** [comment]
全ファイルのアップロード完了
ファイル構造は https://storage.tsukuriga.net/altwug/tree.json に記載済み
